spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/
#  mvc:
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/





